[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "tt"
version = "3.7.32"
description = "CEX & DEX integration with multi messaging platform support and plugin support."
authors = ["mraniki <8766259+mraniki@users.noreply.github.com>"]
license = "MIT License"
readme = "README.md"
keywords = ["finance", "trading", "bot", "chat","DEFI","CEFI","DEX"]
packages = [
    {include = "tt"}
]
classifiers = [
    "Topic :: Trading",
]

[tool.poetry.urls]
"Changelog" =  "https://github.com/mraniki/tt/blob/dev/CHANGELOG.rst"
"Support" =  "https://github.com/mraniki/tt/discussions"
"Issues" =  "https://github.com/mraniki/tt/issues"

[tool.poetry.dependencies]
python = "^3.10"
dynaconf = "^3.1.12"
apprise= "^1.4.0"
httpx = "^0.24.1"
uvicorn = "^0.22.0"
fastapi = "^0.99.0"
ping3 = "^4.0.4"
ccxt = "^4.0.0"
dxsp = "^3.2.0"
findmyorder = "^1.5.4"
iamlistening = "^0.2.7"
talkytrend = "^1.5.9"

[tool.poetry.group.dev.dependencies]
python-semantic-release = "^7.34.3"
sphinx = "^6.0.0"
sphinx_bootstrap_theme = "^0.8.1"

[tool.poetry.group.test.dependencies]
pytest = "^7.0"
pytest-cov = "^4.1"
pytest-asyncio = "^0.21.0"
pytest-mock = "^3.11.1"

[tool.poetry.group.docs.dependencies]
sphinx-autoapi = "^2.1.1"
furo = "2023.5.20"
myst-parser = "^2.0.0"
sphinx_inline_tabs= "^2023.4.21"
sphinx-copybutton= "^0.5.2"
sphinx-reredirects = "*"
sphinx_design = "*"
sphinx-notfound-page = "*"

[tool.pytest.ini_options]
pythonpath = "."
testpaths = "tests"
python_classes = "Test*"
log_format = "%(asctime)s - %(levelname)s - %(name)s - %(message)s"
log_level = "DEBUG"
filterwarnings = [
    " ignore:.*U.*mode is deprecated:DeprecationWarning",
]

[tool.coverage.run]
omit = [
    "tests/*",
    "examples/*",
    "docs/*",
    "*/config.py"
]


[tool.semantic_release]
version_variable = ["pyproject.toml:version","tt/utils.py:__version__"]
branch = "main"
upload_to_pypi = false
upload_to_release = false
build_command = false
remove_dist = false
commit_parser = "semantic_release.history.emoji_parser"
use_textual_changelog_sections = true
changelog_sections = "breaking, feature, fix, documentation"
major_emoji = "BREAKING,💥,:boom:"
minor_emoji = "feat,🥚,:egg:,🚀,:rocket:,💄,:lipstick:,✨,:sparkles:"
patch_emoji = "fix,bump,Update,🎨,:art:,🐛,:bug:,🚑,:ambulance:,⚡,:zap:,🔥,:fire:,🚨,:rotating_light:,♻️,:recycle:,🔧,:wrench:,⬆️,:arrow_up:,🩹,:adhesive_bandage:,👷,:construction_worker:,📝,:memo:,🔒,:lock:,👽,:alien:,💬,:speech_balloon:,🥅,:goal_net:,✅,:white_check_mark:,🐳,:whale:,🙈,:see_no_evil:,⚗️,:alembic:,🧐,:monocle_face:,🔇,:mute:,🔊:volume:"
