[tool.poetry]
name = "tt"
version = "1.3.2"
description = "CEX & DEX integration with multi messaging platform support."
authors = ["mraniki <8766259+mraniki@users.noreply.github.com>"]
license = "MIT License"
readme = "README.md"


[tool.poetry.urls]
"Changelog" =  "https://github.com/mraniki/tt/blob/dev/CHANGELOG.rst"
"Support" =  "https://github.com/mraniki/tt/discussions"
"Issues" =  "https://github.com/mraniki/tt/issues"

[tool.poetry.dependencies]
python = "^3.10"
asyncio = "*"
python-dotenv = "*"
ping3 = "*"
dynaconf = "*"
dxsp = "*"
ccxt = "*"

[tool.poetry.dev-dependencies]
python-semantic-release = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.semantic_release]
version_variable = ["pyproject.toml:version","src/bot.py:__version__"]
branch = "main"
upload_to_pypi = false
upload_to_release = true
build_command = false


