[tool.poetry]
name = "tt"
version = "3.6.1"
description = "CEX & DEX integration with multi messaging platform support and plugin support."
authors = ["mraniki <8766259+mraniki@users.noreply.github.com>"]
license = "MIT License"
readme = "README.md"
keywords = ["finance", "trading", "bot"]
packages = [
    {include = "tt"}
]

[tool.poetry.urls]
"Changelog" =  "https://github.com/mraniki/tt/blob/dev/CHANGELOG.rst"
"Support" =  "https://github.com/mraniki/tt/discussions"
"Issues" =  "https://github.com/mraniki/tt/issues"

[tool.poetry.dependencies]
python = "^3.10.0"
pytest = "*"
pytest-cov = "*"
pytest-asyncio = "*"
pytest-mock = "*"
httpx = "*"
ping3 = "*"
uvicorn = "*"
fastapi = "*"
ccxt = "^3.1.33"
dynaconf = "^3.1.12"
apprise= "^1.4.0"
dxsp = "*"
findmyorder = "*"
iamlistening = "*"
talkytrend = "*"

[tool.poetry.dev-dependencies]
python-semantic-release = "^7.34.3"


[tool.pytest.ini_options]
pythonpath = "."
testpaths = "tests"
python_classes = "Test*"
log_format = "%(asctime)s - %(levelname)s - %(name)s - %(message)s"
log_level = "DEBUG"
filterwarnings = [
    " ignore:.*U.*mode is deprecated:DeprecationWarning",
]


[tool.coverage.run]
omit = [
    "tests/*",
    "examples/*",
    "tt/config.py"
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.semantic_release]
version_variable = ["pyproject.toml:version","tt/utils.py:__version__"]
branch = "main"
upload_to_pypi = false
upload_to_release = false
build_command = false
remove_dist = false
commit_parser = "semantic_release.history.emoji_parser"
use_textual_changelog_sections = true
major_emoji = "BREAKING,💥,:boom:"
minor_emoji = "feat,🥚,:egg:,🚀,:rocket:,💄,:lipstick:,✨,:sparkles:"
patch_emoji = "fix,Update,🎨,:art:,🐛,:bug:,🚑,⚡,:zap:,🔥,:fire:,🚨,:rotating_light:,♻️,:recycle:,🔧,:wrench:,⬆️|:arrow_up:,🩹,👷,📝,🔒,👽,💬,🥅,✅,:white_check_mark:,🐳,🙈,⚗️,🧐,🔇,🔊"
