[tool.poetry]
name = "tt"
version = "1.8.2"
description = "CEX & DEX integration with multi messaging platform support."
authors = ["mraniki <8766259+mraniki@users.noreply.github.com>"]
license = "MIT License"
readme = "README.md"

[tool.poetry.urls]
"Changelog" =  "https://github.com/mraniki/tt/blob/dev/CHANGELOG.rst"
"Support" =  "https://github.com/mraniki/tt/discussions"
"Issues" =  "https://github.com/mraniki/tt/issues"

[tool.poetry.dependencies]
python = "^3.10"
pytest = "*"
pytest-cov = "*"
pytest-asyncio = "*"
dxsp = "^2.6.6"
findmyorder = "^1.3.21"
uvicorn = "*"
ping3 = "*"
fastapi = "*"
ccxt = "*"
dynaconf = "*"
apprise= "*"
telethon= "*"
py-cord= "*"
simplematrixbotlib= "*"

[tool.poetry.dev-dependencies]
python-semantic-release = "*"


[tool.pytest.ini_options]
pythonpath = "src"
testpaths = "tests"
python_classes = "Test*"
log_format = "%(asctime)s - %(levelname)s - %(name)s - %(message)s"
log_level = "DEBUG"

[tool.coverage.run]
omit = [
    "tests/*",
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.semantic_release]
version_variable = ["pyproject.toml:version","src/bot.py:__version__"]
branch = "main"
upload_to_pypi = false
upload_to_release = false
build_command = false
remove_dist = false
commit_parser = "semantic_release.history.emoji_parser"
use_textual_changelog_sections = true
major_emoji = "💥"
minor_emoji = "🥚,🚀,💄,✨"
patch_emoji = "🎨,🐛,🚑,⚡,🔥,🚨,♻️,🔧,⬆️,🩹,👷,📝,🔒,👽,💬,🥅,✅,🐳,🙈,⚗️,🧐,🔇,🔊"
