[default]
loglevel = 'INFO'
host = "0.0.0.0"
port = 8080

bot_token = ''
bot_channel_id = ''

telethon_api_id = ''
telethon_api_hash = ''

matrix_hostname = ''
matrix_user = ''
matrix_pass = ''

discord_webhook_id = ''
discord_webhook_token = ''

dex_name = 'UNISWAP_V2'
dex_chain_id = 1
dex_wallet_address = ''
dex_private_key = ''

dex_testmode = 'False'
dex_rpc = 'https://rpc.ankr.com/optimism"'
dex_router = '0x5c69bee701ef814a2b6a3edd4b1652cb9cc5aa6f' #uniswap v2
dex_base_trading_symbol = 'USDC'
dex_block_explorer_api = ''
dex_protocol = '1inch'
dex_amount_trading_option = '1'

cex_name = 'binance'
cex_api = ''
cex_secret = ''
cex_password = ''
cex_testmode = 'True'
cex_defaulttype = 'spot'
cex_ordertype = 'MARKET'
cex_base_trading_symbol = ''

[DEV]
loglevel = 'DEBUG'


[TT01]
loglevel = 'INFO'

cex_name = 'kraken'
cex_api = ''
cex_secret = ''
cex_password = ''
cex_testmode = 'True'
cex_defaulttype = 'spot'
cex_ordertype = 'MARKET'

port = 8081
