[default]
loglevel = 'INFO'
host = "0.0.0.0"
port = 8080

bot_token = ''
bot_channel_id = ''

telethon_api_id = ''
telethon_api_hash = ''

matrix_hostname = ''
matrix_user = ''
matrix_pass = ''

discord_webhook_id = ''
discord_webhook_token = ''

dex_name = ''
dex_chain_id = 1
dex_wallet_address = ''
dex_private_key = ''

dex_testmode = ''
dex_rpc = ''
dex_router = '' # v2
dex_base_trading_symbol = ''
dex_block_explorer_api = ''
dex_protocol = '1inch'
dex_amount_trading_option = '1'

cex_name = 'binance'
cex_api = ''
cex_secret = ''
cex_password = ''
cex_testmode = ''
cex_defaulttype = ''
cex_ordertype = ''
cex_base_trading_symbol = ''

[DEV]
loglevel = 'DEBUG'