[default]
LOGLEVEL = 'INFO'
HOST = "0.0.0.0"
PORT = 8080

BOT_TOKEN = ''
BOT_CHANNEL_ID = ''

TELETHON_API_ID = ''
TELETHON_API_HASH = ''

MATRIX_HOSTNAME = ''
MATRIX_USER = ''
MATRIX_PASS = ''

DISCORD_WEBHOOK_ID = ''
DISCORD_WEBHOOK_TOKEN = ''

DEX_NAME = 'UNISWAP_V2'
DEX_CHAINID = 1
DEX_WALLET_ADDRESS = ''
DEX_PRIVATE_KEY = ''
DEX_BASE_TRADING_SYMBOL = ''
DEX_BLOCK_EXPLORER_API = ''
DEX_PROTOCOL = ''
DEX_AMOUNT_TRADING_OPTION = ''

CEX_NAME = 'binance'
CEX_API = ''
CEX_SECRET = ''
CEX_PASSWORD = ''
CEX_TESTMODE = 'True'
CEX_DEFAULTTYPE = 'spot'
CEX_ORDERTYPE = 'MARKET'

[DEV]
LOGLEVEL = 'DEBUG'

[TT01]
LOGLEVEL = 'INFO'
PORT = 8081