########################################
###          DEFAULT SETTINGS        ###
########################################

# Any of those settings can be changed 
# by the user. To overwrite a setting, 
# create a settings.toml or load from 
# .env file or env vars.
# As an example, to change the port:
#
#   settings.toml
#   [default]
#    port = 8081
#
# or via .env 
# export TT_PORT=8081


########################################
###        DYNACONF SETTINGS         ###
########################################

[default]
# ENV_FOR_DYNACONF=DEFAULT
VALUE = "Production - Default"

########################################
###         PYTHON SETTINGS          ###
########################################

loglevel = "INFO"
# TT_LOGLEVEL=DEBUG

########################################
###         FASTAPI SETTINGS         ###
########################################

host = "0.0.0.0"
port = 8080

# Your webhook secret to send
# trade alert directly to your
# bot.
webhook_secret = "123abc"

########################################
###        APPRISE SETTINGS          ###
########################################

apprise_api_endpoint = ""
apprise_config = ""
apprise_url = "json://localhost"
apprise_format = "NotifyFormat.MARKDOWN"
# TT_APPRISE_URL='tgram://TOKEN/CHAT_ID'


########################################
###      IAMLISTENING SETTINGS       ###
########################################

iamlistening_enabled = true
bot_token = ""
bot_channel_id = ""
telethon_api_id = ""
telethon_api_hash = ""
matrix_hostname = ""
matrix_user = ""
matrix_pass = ""


########################################
###   CHAT BOT COMMANDS SETTINGS     ###
########################################

bot_prefix = "/"
bot_ignore = "🗿 ⚠️ 📊 🏦 ⬇️ ⬆️"
bot_command_help = "help"
bot_command_bal = "bal"
bot_command_pos = "pos"
bot_command_trading = "trading"
bot_command_restart = "restart"
bot_command_pnl_daily = "d"
bot_command_quote = "q"
bot_command_trend = "trend"
bot_command_news = "live"


########################################
###         TRADING SETTINGS         ###
########################################

trading_enabled = true
trading_risk_amount = 10


########################################
###         PLUGINS SETTINGS         ###
########################################

plugin_enabled = true
plugin_directory = "tt.plugins.default_plugins"
example_plugin_enabled = false
example_plugin_schedule_enabled = false
user_plugins_allowed = false


########################################
###          HELPER SETTINGS         ###
########################################

helper_enabled = true
bot_msg_help = "🏦<code>/bal</code>\n🎯<code>buy BTCUSDT</code>\n🏷️<code>/q BTCB</code>\n🔀<code>/trading</code>"
ping = "8.8.8.8"


########################################
###        FINDMYORDER SETTINGS      ###
########################################

findmyorder_enabled = true
action_identifier = "BUY SELL LONG SHORT"
stop_loss_identifier = "sl="
take_profit_identifier = 'tp='
quantity_identifier = 'q='
order_type_identifier = "spot future margin"
leverage_type_identifier = "cross isolated"
comment_identifier = "comment="
stop_loss = 1000
take_profit = 1000
quantity = 1
instrument_mapping = true
mapping = [
    { id = "GOLD", alt = "XAUUSD" },
    { id = "SILVER", alt = "XAGUSD" },
    { id = "BTC", alt = "WBTC" },
    { id = "ETH", alt = "WETH" },
]
ignore_instrument = "US500 USTEC DOGE"


########################################
###           CCXT SETTINGS          ###
########################################

cex_enabled = false
cex_name = ""
cex_api = ""
cex_secret = ""
cex_password = ""
cex_testmode = true
cex_defaulttype = "SPOT"
cex_ordertype = "MARKET"


########################################
###           DXSP SETTINGS          ###
########################################

dxsp_enabled = true
dex_wallet_address = "0x1234567890123456789012345678901234567890"
dex_private_key = "0xdeadbeef"
dex_protocol_type = "uniswap" #0x 
dex_protocol_version = 2
dex_rpc = "https://rpc.ankr.com/eth"
dex_0x_url = "https://api.0x.org/mainnet"
dex_0x_api_key = "" 
trading_asset_address = "0xdAC17F958D2ee523a2206206994597C13D831ec7"
dex_trading_slippage = 2
dex_block_explorer_url = "https://api.etherscan.io/api?"
dex_block_explorer_api =  "11111111111111111"
dex_router_contract_addr = "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D" 
dex_router_abi_url = "https://raw.githubusercontent.com/uniswap-python/uniswap-python/master/uniswap/assets/uniswap-v2/router02.abi"
dex_factory_contract_addr = "0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f"
dex_erc20_abi_url = "https://raw.githubusercontent.com/Uniswap/interface/44c355c7f0f8ab5bdb3e0790560e84e59f5666f7/src/abis/erc20.json"
dex_notify_invalid_token = true
headers = {User-Agent= 'Mozilla/5.0'}
token_mainnet_list = "https://raw.githubusercontent.com/mraniki/tokenlist/main/all.json"
token_testnet_list = "https://raw.githubusercontent.com/mraniki/tokenlist/main/testnet.json"
token_personal_list = "https://raw.githubusercontent.com/mraniki/tokenlist/main/TT.json"


########################################
###        TALKYTREND SETTINGS       ###
########################################

talkytrend_enabled = true
scanner_frequency = 86400
enable_signals = true
assets = [
    { id ="EURUSD", exchange='FX_IDC',screener="forex"},
    { id ="BTCUSD",exchange="BINANCE",screener="crypto"},
]
enable_events = true
economic_calendar = "https://nfs.faireconomy.media/ff_calendar_thisweek.json"
fomc_decision_date = ["2023-09-20","2023-11-01","2023-12-13"]
live_tv_url = "https://bloomberg.com/media-manifest/streams/us.m3u8"
enable_feed = true
news_feed="https://www.dailyfx.com/feeds/market-news"
enable_news = false
news_url= ""
news_api_key = ""


########################################
###     END OF DEFAULT SETTINGS      ###
########################################




                                        
# _   _                           _   ___  
#| | | |                         | | |__ \ 
#| |_| |__   ___    ___ _ __   __| |    ) |
#| __| '_ \ / _ \  / _ \ '_ \ / _` |   / / 
#| |_| | | |  __/ |  __/ | | | (_| |  |_|  
# \__|_| |_|\___|  \___|_| |_|\__,_|  (_)  
########################################                                                                                      






########################################
###         TESTING SETTINGS         ###
########################################
# Any of those settings are used 
# for testing purpose.
# It can be ignored. 

[testing]
VALUE = "On Testing"
loglevel = "DEBUG"
host = "0.0.0.0"
port = 8080
webhook_secret = "123abc"
apprise_api_endpoint = ""
apprise_config = ""
apprise_url = "json://localhost"
apprise_format = "NotifyFormat.MARKDOWN"
iamlistening_enabled = true
bot_token = ""
bot_channel_id = ""
telethon_api_id = ""
telethon_api_hash = ""
matrix_hostname = ""
matrix_user = ""
matrix_pass = ""
bot_prefix = "/"
bot_ignore = "🗿 ⚠️ 📊 🏦 ⬇️ ⬆️"
bot_command_help = "help"
bot_command_bal = "bal"
bot_command_pos = "pos"
bot_command_trading = "trading"
bot_command_restart = "restart"
bot_command_pnl_daily = "d"
bot_command_quote = "q"
bot_command_trend = "trend"
bot_command_news = "live"
trading_enabled = true
trading_risk_amount = 10
plugin_enabled = true
plugin_directory = "tt.plugins.default_plugins"
example_plugin_enabled = true
user_plugins_allowed = false
helper_enabled = true
bot_msg_help = "🏦<code>/bal</code>\n🎯<code>buy BTCUSDT</code>\n🏷️<code>/q BTCB</code>\n🔀<code>/trading</code>"
ping = "8.8.8.8"
findmyorder_enabled = true
action_identifier = "BUY SELL LONG SHORT"
stop_loss_identifier = "sl="
take_profit_identifier = 'tp='
quantity_identifier = 'q='
order_type_identifier = "spot future margin"
leverage_type_identifier = "cross isolated"
comment_identifier = "comment="
stop_loss = 1000
take_profit = 1000
quantity = 1
instrument_mapping = true
mapping = [
    { id = "GOLD", alt = "XAUUSD" },
    { id = "SILVER", alt = "XAGUSD" },
    { id = "BTC", alt = "WBTC" },
    { id = "ETH", alt = "WETH" },
]
ignore_instrument = "US500 USTEC DOGE"
cex_enabled = false
cex_name = ""
cex_api = ""
cex_secret = ""
cex_password = ""
cex_testmode = true
cex_defaulttype = "SPOT"
cex_ordertype = "MARKET"
dxsp_enabled = true
dex_wallet_address = "0x1234567890123456789012345678901234567890"
dex_private_key = "0xdeadbeef"
dex_protocol_type = "uniswap" #0x 
dex_protocol_version = 2
dex_rpc = "https://rpc.ankr.com/eth"
dex_0x_url = "https://api.0x.org/mainnet"
dex_0x_api_key = "" 
trading_asset_address = "0xdAC17F958D2ee523a2206206994597C13D831ec7"
dex_trading_slippage = 2
dex_block_explorer_url = "https://api.etherscan.io/api?"
dex_block_explorer_api =  "11111111111111111"
dex_router_contract_addr = "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D" 
dex_router_abi_url = "https://raw.githubusercontent.com/uniswap-python/uniswap-python/master/uniswap/assets/uniswap-v2/router02.abi"
dex_factory_contract_addr = "0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f"
dex_erc20_abi_url = "https://raw.githubusercontent.com/Uniswap/interface/44c355c7f0f8ab5bdb3e0790560e84e59f5666f7/src/abis/erc20.json"
dex_notify_invalid_token = true
headers = {User-Agent= 'Mozilla/5.0'}
token_mainnet_list = "https://raw.githubusercontent.com/mraniki/tokenlist/main/all.json"
token_testnet_list = "https://raw.githubusercontent.com/mraniki/tokenlist/main/testnet.json"
token_personal_list = "https://raw.githubusercontent.com/mraniki/tokenlist/main/TT.json"
talkytrend_enabled = true
scanner_frequency = 86400
enable_signals = true
assets = [
    { id ="EURUSD", exchange='FX_IDC',screener="forex"},
    { id ="BTCUSD",exchange="BINANCE",screener="crypto"},
]
enable_events = true
economic_calendar = "https://nfs.faireconomy.media/ff_calendar_thisweek.json"
fomc_decision_date = ["2023-09-20","2023-11-01","2023-12-13"]
live_tv_url = "https://bloomberg.com/media-manifest/streams/us.m3u8"
enable_feed = true
news_feed="https://www.dailyfx.com/feeds/market-news"
enable_news = false
news_url= ""
news_api_key = ""


[cex]
VALUE = "On Testing CEX_binance"
apprise_url = "json://localhost"
apprise_format = "NotifyFormat.MARKDOWN"
plugin_directory = "tt.plugins.default_plugins"
cex_name = 'binance'
cex_api = 'api_key'
cex_secret = 'secret_key'
cex_password = 'password'
cex_defaulttype = 'spot'
cex_testmode = true
helper_enabled = true
talkytrend_enabled = true

[bsc]
VALUE = "On Testing DEX_56"
bot_token = "test_bot_token"
bot_channel_id = "1234567890"
apprise_url = "json://localhost"
apprise_format = "NotifyFormat.MARKDOWN"
trading_enabled = true
trading_asset_address = "0xe9e7cea3dedca5984780bafc599bd69add087d56"
plugin_directory = "tt.plugins.default_plugins"
helper_enabled = true
ping = "8.8.8.8"
dex_wallet_address = "0x1234567890123456789012345678901234567899"
dex_private_key = "0xdeadbeet"
dex_rpc = "https://eth.llamarpc.com"
dex_router_contract_addr = "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D"
dex_factory_contract_addr = "0xcA143Ce32Fe78f1f7019d7d551a6402fC5350c73"
talkytrend_enabled = true
