
#########################################################
###                           DEFAULT SETTINGS        ###
#########################################################
# Any of those settings can be overwritten by the user.
# To overwrite a setting, create a settings.toml
# or load the settings from .env file or vars.
# As an example, to change the port settings:
# settings.toml
# [default]
# port = 8081
# or via ENVVARS 
# export TT_PORT=8081

[default]
VALUE = "Production - Default"
loglevel = "INFO"

# FASTAPI #######
host = "0.0.0.0"
port = 8080
webhook_secret = "123abc"

# APPRISE #######
apprise_api_endpoint = ""
apprise_config = ""
apprise_url = "json://localhost" 
#tgram://TOKEN/CHAT_ID

# PLUGIN ########
plugin_enabled = true
plugin_menu = "plugin"
example_plugin_enabled = false

# IAMLISTENING ##
iamlistening_enabled = true
bot_token = ""
bot_channel_id = ""
telethon_api_id = ""
telethon_api_hash = ""
matrix_hostname = ""
matrix_user = ""
matrix_pass = ""


# BOTCOMMAND #####
bot_prefix = "/"
bot_command_help = "help"
bot_command_bal = "bal"
bot_command_quote = "q"
bot_command_pos = "pos"
bot_command_trading = "trading"
bot_command_news = "live"
bot_command_restart = "restart"
bot_ignore = "🗿 ⚠️ 📊 🏦 ⬇️ ⬆️"

# HELPER #########
helper_enabled = true
bot_msg_help = "🏦<code>/bal</code> 🎯<code>buy BTCUSDT</code> 🏷️<code>/q BTCB</code> 🔀<code>/trading</code>"
ping = "8.8.8.8"
reporting_enabled = false

# TRADING ########
trading_enabled = true
trading_asset = "USDT"
trading_risk_address = "0xdAC17F958D2ee523a2206206994597C13D831ec7"
trading_risk_amount = 10
trading_stop_loss = 1000
trading_take_profit = 1000
exchange_enabled = true

# FINDMYORDER #####
findmyorder_enabled = true
action_identifier = "BUY SELL LONG SHORT"
stop_loss_identifier = "sl="
take_profit_identifier = 'tp='
quantity_identifier = 'q='
order_type_identifier = "spot future margin"
leverage_type_identifier = "cross isolated"
comment_identifier = "comment="
stop_loss = 1000
take_profit = 1000
quantity = 1

# CEX #############
cex_enabled = false
cex_name = ""
cex_api = ""
cex_secret = ""
cex_password = ""
cex_testmode = true
cex_defaulttype = "SPOT"
cex_ordertype = "MARKET"

# DXSP ############
dxsp_enabled = true
dex_wallet_address = "0x1234567890123456789012345678901234567890"
dex_private_key = "0xdeadbeef"
dex_protocol_type = "uniswap" #0x 
dex_protocol_version = 2
dex_rpc = "https://rpc.ankr.com/eth"
dex_block_explorer_url = "https://api.etherscan.io/api?"
dex_block_explorer_api =  "11111111111111111"
dex_router_contract_addr = "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D" #UNI_V2
dex_router_abi_url = "https://raw.githubusercontent.com/uniswap-python/uniswap-python/master/uniswap/assets/uniswap-v2/router02.abi"
dex_factory_contract_addr = "0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f"
dex_erc20_abi_url = "https://raw.githubusercontent.com/Uniswap/interface/44c355c7f0f8ab5bdb3e0790560e84e59f5666f7/src/abis/erc20.json"
dex_0x_url = "https://api.0x.org/mainnet"
dex_0x_api_key = "" 
headers = {User-Agent= 'Mozilla/5.0'}
token_mainnet_list = "https://raw.githubusercontent.com/mraniki/tokenlist/main/all.json"
token_testnet_list = "https://raw.githubusercontent.com/mraniki/tokenlist/main/testnet.json"
token_personal_list = "https://raw.githubusercontent.com/mraniki/tokenlist/main/TT.json"
dex_trading_slippage = 2 # 2 % slippage

# TALKYTREND #######
talkytrend_enabled = true
scanner_frequency = 86400
enable_signals = false
assets = [
    { id ="EURUSD", exchange='FX_IDC',screener="forex", interval = "4h" },
    { id ="BTCUSD",exchange="BINANCE",screener="crypto", interval = "4h"},
]
enable_events = true
# enable_news = false
# news_url= ""
# news_api_key = ""
# live_tv_url = ""



###############################
###      TESTING SETTINGS   ###
###############################

# Any of those settings are used as part of the testing environment.
# It can be ignored. If you required to support multiple environments in 
# your application, you can create a part like this:
# [mycexconfig1]
# VALUE = "MYCEX details"
# [mycexconfig2]
# VALUE = "MYCEX2 details"


[testing]
VALUE = "On Testing"
telethon_api_id = "123456789"
telethon_api_hash = "123456789"
bot_token = "test_bot_token"
bot_channel_id = "1234567890"
helper_enabled = true
exchange_enabled = true
trading_enabled = true
cex_name = ""
dxsp_enabled = true
headers = {User-Agent= 'Mozilla/5.0'}
token_mainnet_list = "https://raw.githubusercontent.com/mraniki/tokenlist/main/all.json"
token_testnet_list = "https://raw.githubusercontent.com/mraniki/tokenlist/main/testnet.json"
token_personal_list = "https://raw.githubusercontent.com/mraniki/tokenlist/main/TT.json"
dex_trading_slippage = 2 
dex_wallet_address = "0x1234567890123456789012345678901234567890"
dex_private_key = "0xdeadbeef" 
dex_protocol_type = "uniswap_v2"
dex_rpc = "https://rpc.ankr.com/eth"
dex_block_explorer_url = "https://api.etherscan.io/api?"
dex_block_explorer_api =  "798437294880920392" 
dex_router_contract_addr = "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D" #UNI_V2
dex_router_abi_url = "https://raw.githubusercontent.com/uniswap-python/uniswap-python/master/uniswap/assets/uniswap-v2/router02.abi"
dex_factory_contract_addr = "0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f"
dex_erc20_abi_url = "https://raw.githubusercontent.com/Uniswap/interface/44c355c7f0f8ab5bdb3e0790560e84e59f5666f7/src/abis/erc20.json"
webhook_secret = "123abc"
bot_prefix = "/"
bot_command_help = "help"
bot_command_bal = "bal"
bot_command_quote = "q"
bot_command_pos = "pos"
bot_command_trading = "trading"
bot_command_news = "live"
bot_command_restart = "restart"
bot_ignore = "🗿 ⚠️ 📊 🏦 ⬇️ ⬆️"
bot_msg_help = "🏦 <code>/bal</code> 📦 <code>buy BTCUSDT</code> 🔀 <code>/trading</code>"
example_plugin_enabled = true
ping = "8.8.8.8"
apprise_url = "json://localhost"

[cex]
exchange_enabled = true
cex_enabled = true
helper_enabled = true
VALUE = "On Testing CEX_binance"
cex_name = 'binance'
cex_api = 'api_key'
cex_secret = 'secret_key'
cex_password = 'password'
cex_defaulttype = 'spot'
cex_testmode = true
dex_chain_id = ""
apprise_url = "json://localhost"

[bsc]
VALUE = "On Testing DEX_56"
helper_enabled = true
cex_name = ""
dex_wallet_address = "0x1234567890123456789012345678901234567899"
dex_private_key = "0xdeadbeet"
dex_rpc = "https://eth.llamarpc.com"
dex_router_contract_addr = "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D"
dex_factory_contract_addr = "0xcA143Ce32Fe78f1f7019d7d551a6402fC5350c73"
trading_enabled = true
bot_token = "test_bot_token"
bot_channel_id = "1234567890"
ping = "8.8.8.8"
apprise_url = "json://localhost"


# [zerox]
# VALUE = "On Testing 0x_DEX_1"
# helper_enabled = true
# cex_name = ""
# dex_wallet_address = "0x1234567890123456789012345678901234567899"
# dex_private_key = "0xdeadbeet"
# dex_rpc = "https://eth.llamarpc.com"
# dex_protocol_type = "0x"
# dex_router_contract_addr = "0xdef1c0ded9bec7f1a1670819833240f027b25eff"
# dex_factory_contract_addr = ""
# trading_enabled = true
# matrix_hostname = "https://matrix.org"
# matrix_user = "@thismock:matrix.org"
# matrix_pass = "1234"
# bot_token = "token_123435"
# bot_channel_id = "1234567890"
# ping = "8.8.8.8"
# apprise_url = "json://localhost"