########################################
###          DEFAULT SETTINGS        ###
########################################

# Any of those settings can be changed 
# by the user. To overwrite a setting, 
# create a settings.toml or load from 
# .env file or env vars.
# As an example, to change the port:
#
#   settings.toml
#   [default]
#    port = 8081
#
# or via .env 
# export TT_PORT=8081


########################################
###        DYNACONF SETTINGS         ###
########################################

[default]
# ENV_FOR_DYNACONF=DEFAULT
VALUE = "Production - Default"


########################################
###         PYTHON SETTINGS          ###
########################################

loglevel = "INFO"
# TT_LOGLEVEL=DEBUG

########################################
###         FASTAPI SETTINGS         ###
########################################

host = "0.0.0.0"
port = 8080

# Your webhook secret to send
# trade alert directly to your
# bot.
webhook_secret = "123abc"
forwarder = false
forwarder_url = ""

########################################
###        APPRISE SETTINGS          ###
########################################

apprise_url = "json://localhost"
apprise_format = "NotifyFormat.MARKDOWN"
# TT_APPRISE_URL='tgram://TOKEN/CHAT_ID'


########################################
###      IAMLISTENING SETTINGS       ###
########################################

iamlistening_enabled = true
chat_platform=""
bot_token = ""
bot_channel_id = ""
bot_api_id = ""
bot_api_hash = ""
bot_hostname = ""
bot_user = ""
bot_pass = ""
bot_auth_token = ""
iteration_enabled = false
iteration_limit = -1

########################################
###   COMMON BOT COMMAND SETTINGS    ###
########################################

bot_prefix = "/"
bot_ignore = "🗿 ⚠️ 📊 🏦 ⬇️ ⬆️"
bot_command_help = "help"
bot_command_info = "info"
bot_command_bal = "bal"
bot_command_pos = "pos"
bot_command_pnl_daily = "d"
bot_command_quote = "q"


########################################
###         TRADING SETTINGS         ###
########################################

trading_enabled = true
trading_risk_amount = 10


########################################
###         PLUGINS SETTINGS         ###
########################################

plugin_enabled = true
plugin_directory = "tt.plugins.default_plugins"
example_plugin_enabled = false
user_plugins_allowed = false


########################################
###          HELPER SETTINGS         ###
########################################

helper_enabled = true
helper_commands = "🔀 /trading\n🔁 /restart\n🕸️ /network"
bot_command_trading = "trading"
bot_command_network = "network"
bot_command_restart = "restart"
ping = "8.8.8.8"

########################################
###           WWW SETTINGS           ###
########################################

www_enabled = true
www_commands = "📷 /src\n"
bot_command_screenshot = "scr"
www_url = "https://apod.nasa.gov/apod/astropix.html"


########################################
###           LLM SETTINGS           ###
########################################

llm_enabled = true
llm_model = "gpt-4"
llm_provider = "g4f.Provider.Providers.ChatgptAi"
llm_host = ""
llm_auth_token = ""
llm_default_prompt = "write a tiny story"
llm_commands = "🦾 /qq\n"
bot_command_question = "qq"


########################################
###        FINDMYORDER SETTINGS      ###
########################################

findmyorder_enabled = true
action_identifier = "BUY SELL LONG SHORT"
stop_loss_identifier = "sl="
take_profit_identifier = 'tp='
quantity_identifier = 'q='
order_type_identifier = "spot future margin"
leverage_type_identifier = "cross isolated"
comment_identifier = "comment="
stop_loss = 1000
take_profit = 1000
quantity = 1
instrument_mapping = true
mapping = [
    { id = "GOLD", alt = "XAUUSD" },
    { id = "SILVER", alt = "XAGUSD" },
    { id = "BTC", alt = "WBTC" },
    { id = "ETH", alt = "WETH" },
]
ignore_instrument = "US500 USTEC DOGE"


########################################
###           CCXT SETTINGS          ###
########################################

cex_enabled = false
ccxt_commands = "🎯 BUY BTCUSDT\n🎯 /q BTCUSDT\n🏦 /bal\n🏦 /pos\n"
cex_name = ""
cex_api = ""
cex_secret = ""
cex_password = ""
cex_testmode = true
cex_defaulttype = "SPOT"
cex_ordertype = "MARKET"


########################################
###           DXSP SETTINGS          ###
########################################

dxsp_enabled = true
dxsp_commands = "🎯 BUY WBTC\n🎯 /q WBTC\n 🏦 /bal\n 🏦 /pos\n"
dex_wallet_address = "0x1234567890123456789012345678901234567890"
dex_private_key = "0xdeadbeef"
dex_protocol_type = "uniswap" #0x 
dex_protocol_version = 2
dex_rpc = "https://rpc.ankr.com/eth"
dex_0x_url = "https://api.0x.org/mainnet"
dex_0x_api_key = "" 
trading_asset_address = "0xdAC17F958D2ee523a2206206994597C13D831ec7"
dex_trading_slippage = 2
dex_block_explorer_url = "https://api.etherscan.io/api?"
dex_block_explorer_api =  "11111111111111111"
dex_router_contract_addr = "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D" 
dex_router_abi_url = "https://raw.githubusercontent.com/uniswap-python/uniswap-python/master/uniswap/assets/uniswap-v2/router02.abi"
dex_factory_contract_addr = "0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f"
dex_erc20_abi_url = "https://raw.githubusercontent.com/Uniswap/interface/44c355c7f0f8ab5bdb3e0790560e84e59f5666f7/src/abis/erc20.json"
dex_notify_invalid_token = true
headers = {User-Agent= 'Mozilla/5.0'}
token_mainnet_list = "https://raw.githubusercontent.com/mraniki/tokenlist/main/all.json"
token_testnet_list = "https://raw.githubusercontent.com/mraniki/tokenlist/main/testnet.json"
token_personal_list = "https://raw.githubusercontent.com/mraniki/tokenlist/main/TT.json"


########################################
###        TALKYTREND SETTINGS       ###
########################################

talkytrend_enabled = true
talkytrend_commands = "📺 /live\n📰 /news\n📊 /trend"
bot_command_tv = "live"
bot_command_trend = "trend"
bot_command_news = "news"
enable_signals = true
assets = [
    { id ="EURUSD", exchange='FX_IDC',screener="forex"},
    { id ="BTCUSD",exchange="BINANCE",screener="crypto"},
]
enable_events = true
economic_calendar = "https://nfs.faireconomy.media/ff_calendar_thisweek.json"
fomc_decision_date = ["2023-09-20","2023-11-01","2023-12-13"]
live_tv_url = "https://bloomberg.com/media-manifest/streams/us.m3u8"
enable_feed = true
news_feed="https://www.dailyfx.com/feeds/market-news"


########################################
###     END OF DEFAULT SETTINGS      ###
########################################





                                        
# _   _                           _   ___  
#| | | |                         | | |__ \ 
#| |_| |__   ___    ___ _ __   __| |    )|
#| __| '_ \ / _ \  / _ \ '_ \ / _` |   / / 
#| |_| | | |  __/ |  __/ | | | (_| |  |_|  
# \__|_| |_|\___|  \___|_| |_|\__,_|  (_)  
########################################     
#
#
#
#
#         __     __       
#         \ \   / /       
#          \ \_/ /__  ___ 
#           \   / _ \/ __|
#            | |  __/\__ \
#            |_|\___||___/
#
#
#
#                   
########################################     
