[CEX01]
# TELEGRAM BOT for Binance
# ENV_FOR_DYNACONF="CEX01" # 
bot_token = '28409238409'
bot_channel_id = '-110219301930'
telethon_api_id = '3247289374982'
telethon_api_hash = '993287490238409' 
cex_name = 'binance' 
cex_api = 'asdhjaslkfjhksadhfklash' 
cex_secret = 'sadkfhklasdhjfklajsh' 
cex_password = '' 
cex_testmode = '' 
cex_defaulttype = 'SPOT' 
cex_ordertype = 'MARKET' 
#FindMyOrder custom  config
action_identifier = "BUY MOON"

[DEX01]
#DISCORD BOT on ethereum chain using uniswap v2 router and protocol
# ENV_FOR_DYNACONF="DEX01" # 
bot_token = '9238409284302'
bot_channel_id = '293840284309'
discord_webhook_id = '423423423' 
discord_webhook_token = '32423423' 
#DXSP custom  config
dex_chain_id = 10
dex_wallet_address = '4234234234'
dex_private_key = '234234234'
dex_block_explorer_api = '42342342342'