on:
  push:
    schedule:
      - cron: '0 6 * * *'

jobs:
  check_dep:
    runs-on: ubuntu-latest
    name: Check python requirements file and update
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check requirements.txt
        uses: Verbalinsurection/track-pypi-version@1.1.0
        id: checkr
        with:
          compush: 'true'
          backup: 'false'
          reqfile: './requirements.txt'
      - name: Get if update needed output
        run: echo ${{ steps.checkr.outputs.commit }}
