name: "📦 Latest"

on:
  push:
    branches:
      - "main"
    tags:
      - "latest"

jobs:
  release:
      runs-on: ubuntu-latest
      # needs: [build]
      steps:
        - uses: actions/checkout@v3.5.2
          with:
            fetch-depth: 0
        - name: Python Semantic Release
          uses: relekang/python-semantic-release@v7.33.3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}

  nightly-merge:
    runs-on: ubuntu-latest
    needs: release
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.0
      with:
        fetch-depth: 0

    - name: Nightly Merge
      uses: robotology/gh-action-nightly-merge@v1.4.0
      with:
        stable_branch: 'main'
        development_branch: 'dev'
        allow_ff: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}